---
kind: pipeline
type: docker
trigger:
  event:
  - push
  branch:
  - master
name: default

clone:
  depth: 1

steps:
- name: Generate docs
  image: harbor.zyra.ca/public/zmdocs:v1.1.0
  when:
    branch:
    - master
  commands:
  - zmdocs g

- name: Publish docs
  image: plugins/gh-pages
  when:
    branch:
    - master
  settings:
    username:
      from_secret: gh_user
    password:
      from_secret: gh_token
    pages_directory: docs
---
kind: signature
hmac: f1d5bf6207377918cdbeab9081853fbc934480c13ce964d92ddda5cf3f50ba88

...
